### ISSUE TITLE
No way to run check on all resources within an account, at least stack or tags options are required

### ISSUE THREAD

**Issue by fredericbarthelet** [Kumo-by-Theodo/guardian#38]
I'm working on a application with multiple cloudformation stacks in a monorepo.
I have 2 solutions to cover all resources within my application with Guardian:

- use the `-t` or `--tags` option and use one tag available on all resources. I have such tag, but I run into a rate exceeded error on the `ListVersionsByFunctionCommand` API calls
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23530626/179255014-52b83d78-e808-4f4f-b10a-92d4264c31ce.png">

- use the `-c` or `--cloudformation` option and run one job per stack in my CI. But this results in less readable report as I have to merge all results from all stacks to have a complete overview of my application biggest issue and prioritize where I should implement a good practice first

I have 2 problems I'd like to address with this issue :
- [REQUIRED] be able to run check with `-t` and not encounter a rate exceeded error
- [OPTIONAL] be able to provide more than one stack as argument to `-c` to filter resources based on their stack
- [OPTIONAL] be able to provide no argument `-t` or `-c` and analyse all resources from the account and region specified

WDYT ?

**Comment by PChol22** [comment]
Thanks for your feedback, we took into account your proposals.

With version 0.0.13 of Guardian, we fixed the rate exceeded error you were running into when using -t option in your CI.

We have also added your two other proposals to the list of features we want to implement in the near future: it especially seems important to us to be able to run guardian checks on multiple stacks at the same time.

Stay tuned for next Guardian releases over the coming weeks !
