### ISSUE TITLE
Guardian checks exceeds 1min on large stacks

### ISSUE THREAD

**Issue by fredericbarthelet** [Kumo-by-Theodo/guardian#48]
Hi, I'm facing an issue regarding the required time to run guardian on my account. On average, more than 1 minute is required to complete the checks. Here are some details:

Quantity of Lambda functions:  549
Region: eu-west-1

I believe this might be linked to the account rate limit being hit and retry strategy having to wait for a long time.

Is there any way to reduce the time needed to check all resources ?

**Comment by adelego** [comment]
Hello @fredericbarthelet  ! Thank you for your feedback. 
A fix is available in the latest version 0.0.15. 
We've updated retry strategy to wait longer to be able to fetch resources
