### ISSUE TITLE
Progress bar display shows progress on new line

### ISSUE THREAD

**Issue by fredericbarthelet** [Kumo-by-Theodo/guardian#49]
When using guardian to run checks from my terminal, progress bar is complitely re-displayed on a new line when it progresses

<img width="415" alt="image" src="https://user-images.githubusercontent.com/23530626/181811376-c62682f9-7fa3-4ed6-a581-0d9269205989.png">

My environment is iTerm on Mac OS.

**Comment by PChol22** [comment]
The problem was fixed in version 0.0.16 🚀

**Comment by fredericbarthelet** [comment]
Thanks @PChol22, it works like a charm !
